language: python
python:
        - '3.6'
install:
        - 'pip install pipenv'
        - 'pipenv install'
env: DJANGO_SETTINGS_MODULE="purebutter.settings.travis"

services:
        - postgresql
script:
        - python manage.py test
